services:
  profile.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5000:8080"
      - "5001:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
      - geoip_data:/app/data/geoIp
    networks:
     - backend
    depends_on:
     - sqlserver

  rabbitmq:
    networks: 
     - backend
    ports:
     - "5672:5672"
     - "15672:15672"

  sqlserver:
    ports:
     - 1433:1433
    networks:
     - backend
    volumes: 
     - sqlserverData:/var/opt/mssql
    restart: always
    environment:
    - MSSQL_SA_PASSWORD=hG5rzck2vy3cHai
    - ACCEPT_EULA=Y
  
  redis:
    networks: 
    - backend
    ports: 
    - 6379:6379
    volumes:
     - redis_data:/data
     
  career.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "5002:8080"
      - "5003:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - backend
    depends_on:
      - sqlserver
