//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Career.Domain.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceExceptMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceExceptMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Career.Domain.Exceptions.ResourceExceptMessages", typeof(ResourceExceptMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Company not found.
        /// </summary>
        internal static string COMPANY_NOT_EXISTS {
            get {
                return ResourceManager.GetString("COMPANY_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Company is private, user cannot access this.
        /// </summary>
        internal static string COMPANY_PRIVATE {
            get {
                return ResourceManager.GetString("COMPANY_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Company rate must be between 0 and 5.
        /// </summary>
        internal static string COMPANY_RATE_INVALID {
            get {
                return ResourceManager.GetString("COMPANY_RATE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Request token is null.
        /// </summary>
        internal static string EMPTY_REQUEST_TOKEN {
            get {
                return ResourceManager.GetString("EMPTY_REQUEST_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Occured an error while trying to send email to user.
        /// </summary>
        internal static string ERROR_SENDING_EMAIL {
            get {
                return ResourceManager.GetString("ERROR_SENDING_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid serialization type.
        /// </summary>
        internal static string INVALID_SERIALIZER_TYPE {
            get {
                return ResourceManager.GetString("INVALID_SERIALIZER_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Request bearer token is on an invalid format.
        /// </summary>
        internal static string INVALID_TOKEN_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_TOKEN_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Max salary must be greather or equal than min salary.
        /// </summary>
        internal static string MIN_SALARY_LOWER_THAN_HIGHER {
            get {
                return ResourceManager.GetString("MIN_SALARY_LOWER_THAN_HIGHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Notification message length must be thousand or less.
        /// </summary>
        internal static string NOTIFICATION_MESSAGE_THOUSAND_MAX {
            get {
                return ResourceManager.GetString("NOTIFICATION_MESSAGE_THOUSAND_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Company owner set show staffs as private, you does not have permission to access this.
        /// </summary>
        internal static string SHOW_STAFFS_PRIVATE {
            get {
                return ResourceManager.GetString("SHOW_STAFFS_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Staff does not have permission for hire a staff.
        /// </summary>
        internal static string STAFF_DOESNT_HAVE_PERMISSION_FOR_HIRE {
            get {
                return ResourceManager.GetString("STAFF_DOESNT_HAVE_PERMISSION_FOR_HIRE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Staff already is in company.
        /// </summary>
        internal static string STAFF_IN_COMPANY {
            get {
                return ResourceManager.GetString("STAFF_IN_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot reject staff request, it already was accepted.
        /// </summary>
        internal static string STAFF_REQUEST_ALREADY_ACCEPTED {
            get {
                return ResourceManager.GetString("STAFF_REQUEST_ALREADY_ACCEPTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot accept staff request, it already was rejected.
        /// </summary>
        internal static string STAFF_REQUEST_ALREADY_REJECTED {
            get {
                return ResourceManager.GetString("STAFF_REQUEST_ALREADY_REJECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Staff request was not found.
        /// </summary>
        internal static string STAFF_REQUEST_NOT_EXISTS {
            get {
                return ResourceManager.GetString("STAFF_REQUEST_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Request bearer token is expired.
        /// </summary>
        internal static string TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User already is in company.
        /// </summary>
        internal static string USER_ALREADY_IN_COMPANY {
            get {
                return ResourceManager.GetString("USER_ALREADY_IN_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User can&apos;t see staff request status.
        /// </summary>
        internal static string USER_CANNOT_SEE_STAFF_REQUEST_STATUS {
            get {
                return ResourceManager.GetString("USER_CANNOT_SEE_STAFF_REQUEST_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User must be authenticated for access this endpoint.
        /// </summary>
        internal static string USER_NOT_AUTHENTICATED {
            get {
                return ResourceManager.GetString("USER_NOT_AUTHENTICATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User must be binded to company.
        /// </summary>
        internal static string USER_NOT_BINDED_TO_COMPANY {
            get {
                return ResourceManager.GetString("USER_NOT_BINDED_TO_COMPANY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User must be owner of this company.
        /// </summary>
        internal static string USER_NOT_COMPANY_OWNER {
            get {
                return ResourceManager.GetString("USER_NOT_COMPANY_OWNER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User requested not exists.
        /// </summary>
        internal static string USER_NOT_EXISTS {
            get {
                return ResourceManager.GetString("USER_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User must be the requested to accept this staff request.
        /// </summary>
        internal static string USER_NOT_REQUESTED_ON_STAFF_REQUEST {
            get {
                return ResourceManager.GetString("USER_NOT_REQUESTED_ON_STAFF_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User doesn&apos;t have permission for create company.
        /// </summary>
        internal static string USER_ROLE_OWNER_FOR_CREATE_COMPANY {
            get {
                return ResourceManager.GetString("USER_ROLE_OWNER_FOR_CREATE_COMPANY", resourceCulture);
            }
        }
    }
}
