//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Profile.Domain.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceExceptMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public ResourceExceptMessages() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Profile.Domain.Exceptions.ResourceExceptMessages", typeof(ResourceExceptMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User already is connected to profile.
        /// </summary>
        public static string ALREADY_CONNECTED {
            get {
                return ResourceManager.GetString("ALREADY_CONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User can&apos;t connect with themself.
        /// </summary>
        public static string CONNECT_WITH_YOURSELF {
            get {
                return ResourceManager.GetString("CONNECT_WITH_YOURSELF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid connection id, connection does not exist.
        /// </summary>
        public static string CONNECTION_BY_ID_NOT_EXISTS {
            get {
                return ResourceManager.GetString("CONNECTION_BY_ID_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This e-mail already exists.
        /// </summary>
        public static string EMAIL_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wrong e-mail format.
        /// </summary>
        public static string EMAIL_FORMAT {
            get {
                return ResourceManager.GetString("EMAIL_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User with this e-mail doesn&apos;t exists.
        /// </summary>
        public static string EMAIL_NOT_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail or password invalid
        ///.
        /// </summary>
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The email confirmation token is invalid.
        /// </summary>
        public static string INVALID_EMAIL_TOKEN {
            get {
                return ResourceManager.GetString("INVALID_EMAIL_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Github profile doesn&apos;t exist.
        /// </summary>
        public static string INVALID_GITHUB_PROFILE {
            get {
                return ResourceManager.GetString("INVALID_GITHUB_PROFILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid id format.
        /// </summary>
        public static string INVALID_ID_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_ID_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid url format.
        /// </summary>
        public static string INVALID_URL_FORMAT {
            get {
                return ResourceManager.GetString("INVALID_URL_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Only can accept pending connections.
        /// </summary>
        public static string ONLY_ACCEPT_PENDING_CONNECTION {
            get {
                return ResourceManager.GetString("ONLY_ACCEPT_PENDING_CONNECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Items per page is out of range, the limit is 100.
        /// </summary>
        public static string OUT_OF_RANGE_PER_PAGE_MAX_100 {
            get {
                return ResourceManager.GetString("OUT_OF_RANGE_PER_PAGE_MAX_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password length must be greather or equal 8.
        /// </summary>
        public static string PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Profile does not exist.
        /// </summary>
        public static string PROFILE_NOT_EXISTS {
            get {
                return ResourceManager.GetString("PROFILE_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This profile is private.
        /// </summary>
        public static string PROFILE_PRIVATE {
            get {
                return ResourceManager.GetString("PROFILE_PRIVATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Can&apos;t connect on github server.
        /// </summary>
        public static string REQUEST_GITHUB_ERROR {
            get {
                return ResourceManager.GetString("REQUEST_GITHUB_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This skill does not exist.
        /// </summary>
        public static string SKILL_NOT_EXISTS {
            get {
                return ResourceManager.GetString("SKILL_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The following skills doesn&apos;t exist.
        /// </summary>
        public static string SKILLS_NOT_EXISTS {
            get {
                return ResourceManager.GetString("SKILLS_NOT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a This user does not exists.
        /// </summary>
        public static string USER_DOESNT_EXISTS {
            get {
                return ResourceManager.GetString("USER_DOESNT_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User already has this skill.
        /// </summary>
        public static string USER_HAS_SKILL {
            get {
                return ResourceManager.GetString("USER_HAS_SKILL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User must be authenticated to access this.
        /// </summary>
        public static string USER_NOT_AUTHENTICATED {
            get {
                return ResourceManager.GetString("USER_NOT_AUTHENTICATED", resourceCulture);
            }
        }
    }
}
